# Generated by Django 6.0.7 on 2026-08-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_organization_userprofile_role_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('PendingApproval', 'Pending Approval')], default='Active', max_length=20),
        ),
    ]
