# Generated by Django 6.0.7 on 2026-08-04 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_bugactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tracker.organization')),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bugs', to='tracker.tag'),
        ),
    ]
