# Generated by Django 6.0.7 on 2026-08-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_tag_bug_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
