# Generated by Django 6.0.7 on 2026-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_bug_linked_bugs_comment_parent_savedfilter_worklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='display_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='next_bug_sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
