# Generated by Django 6.0.7 on 2026-08-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_bug_display_id_project_next_bug_sequence_and_more'),
    ]

import uuid

def generate_prefix_and_display_id(apps, schema_editor):
    Project = apps.get_model('tracker', 'Project')
    Bug = apps.get_model('tracker', 'Bug')
    
    for project in Project.objects.all():
        if not project.prefix:
            words = project.name.split()
            if len(words) == 1:
                base_prefix = words[0][:4].upper()
            else:
                base_prefix = "".join(word[0] for word in words[:4]).upper()
            
            base_prefix = "".join(c for c in base_prefix if c.isalnum())
            if not base_prefix:
                base_prefix = "PRJ"
                
            prefix = base_prefix
            counter = 1
            while Project.objects.filter(prefix=prefix).exclude(id=project.id).exists():
                prefix = f"{base_prefix}{counter}"
                counter += 1
            project.prefix = prefix
            project.save(update_fields=['prefix'])

    for bug in Bug.objects.all():
        if not bug.display_id:
            if bug.project:
                project = bug.project
                bug.display_id = f"{project.prefix}-{project.next_bug_sequence}"
                project.next_bug_sequence += 1
                project.save(update_fields=['next_bug_sequence'])
                bug.save(update_fields=['display_id'])
            else:
                bug.display_id = f"BUG-{uuid.uuid4().hex[:6].upper()}"
                bug.save(update_fields=['display_id'])

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_bug_display_id_project_next_bug_sequence_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_prefix_and_display_id, reverse_migration),
    ]
